package com.jaohara.mobileappdev.movie

import android.os.Bundle
import android.util.Log
import androidx.fragment.app.Fragment
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.widget.Toast
import androidx.core.os.bundleOf
import androidx.core.view.get
import androidx.navigation.Navigation
import androidx.navigation.fragment.NavHostFragment
import androidx.recyclerview.widget.LinearLayoutManager
import androidx.recyclerview.widget.RecyclerView
import com.jaohara.mobileappdev.MovieMainFragment
import com.jaohara.mobileappdev.R

class MovieList : Fragment() {
  private var rvMovieList: RecyclerView? = null;

  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
  }

  override fun onCreateView( inflater: LayoutInflater, container: ViewGroup?,
    savedInstanceState: Bundle?): View? {
    return inflater.inflate(R.layout.fragment_movie_list, container, false);
  }

  override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
    super.onViewCreated(view, savedInstanceState);
    rvMovieList = view.findViewById(R.id.rvMovieList);
    fillMovieList();
    styleMovieList();
    setupMovieListClickListeners();

    // test that the call is working
  }

  // Helper Functions
  private fun fillMovieList() {
    rvMovieList?.adapter = context?.let {
      MovieListAdapter(it) { position: Int -> onListItemClick(position) }
    };

    rvMovieList?.layoutManager = context?.let { LinearLayoutManager(it) };
  }

  private fun styleMovieList() {
    rvMovieList?.setBackgroundColor(resources.getColor(R.color.light_gray));
  }

  private fun setupMovieListClickListeners() {
//    rvMovieList.addOnItemTouchListener(RecyclerItemClickListener )
  }


  // Factory method generated by Android Studio
  companion object {
    @JvmStatic
    fun newInstance(movies: Array<String>) =
      MovieList().apply {
        arguments = Bundle().apply {
          putStringArray("movies", movies);
        }
      }
  }

  private fun onListItemClick(position: Int) {
    Log.i("onListItemClick", "Click registered for $position");
    val bundle = bundleOf("position" to position);
    (parentFragment as NavHostFragment).navController.navigate(R.id.movieListToMovieDetail, bundle);
//    Toast.makeText(activity?.applicationContext,
//      (rvMovieList?.adapter as MovieListAdapter).getMovie(position)[0],
//      Toast.LENGTH_SHORT ).show();
  }
}